site_name: "Arg Init"
site_description: "Package to simplify Argument initialisation."
repo_url: "https://github.com/srfoster65/arg_init"
repo_name: "srfoster65/arg_init"
site_dir: "site"
watch: [readme.md, docs/overview.md, docs/usage.md, docs/license.md, docs/changelog.md, docs/reference.md]

theme:
  name: material
  features:
  - content.code.annotate
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  palette:
    primary: blue

nav:
  - Documentation:
    - index.md
    - Usage: usage.md
    - Reference: reference.md
  - Changelog: changelog.md
  - License: license.md

# extra_css:
#   - css/style.css
#   - css/material.css
#   - css/mkdocstrings.css

markdown_extensions:
# - admonition
# - pymdownx.details
# - pymdownx.emoji
# - pymdownx.magiclink
- pymdownx.snippets:
#     check_paths: true
# - pymdownx.superfences
# - pymdownx.tabbed:
#     alternate_style: true
# - pymdownx.tasklist

plugins:
# - section-index
- search
