name: Build distribution

on:
- workflow_call

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PDM
      uses: pdm-project/setup-pdm@v3
      with:
        python-version: 3.11
        cache: true

    - name: Install dependencies
      run: pdm install -G test

    - name: Build a binary wheel and a source tarball
      run: pdm build

    - name: Store the distribution packages
      uses: actions/upload-artifact@v3
      with:
        name: python-package-distributions
        path: dist/
