name: ruff

on:
- workflow_call

jobs:
  build:
    name: ruff
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PDM
      uses: pdm-project/setup-pdm@v3
      with:
        python-version: 3.11
        cache: true

    - name: Install dependencies
      run: pdm install -G test

    - name: Run Ruff check
      run: pdm run ruff check .

    - name: Run Ruff format
      id: ruff_format
      run: pdm run ruff format .

    - name: create badge
      uses: srfoster65/workflow_badge_action@main
      with:
        label: ${{ github.job}}
        status: ${{ steps.ruff_format.outcome }}
